### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by j209** [iondv/framework#16]
Hi. Thanks a lot for your greate work.
Is project active or abandoned?
what is road map?
I believe [Deno](https://github.com/denoland/deno) is the feature of server-side javascript.it would be greate iondv port to deno from node for backend developement.

**Comment by akumidv** [comment]
> 
> 
> Hi. Thanks a lot for your greate work.
> Is project active or abandoned?
> what is road map?
> I believe [Deno](https://github.com/denoland/deno) is the feature of server-side javascript.it would be greate iondv port to deno from node for backend developement.

Hi. Thanks for your question.

Yes, the project active, but we have same issues to realize in the core support for i18n. Now it almost ready. All things ready in branch `russian`. We tested them. But we don't finish translation of code from Russian to English yet .
We plan finish in february also with new documentation version. See https://github.com/iondv/docs-l10n

We haven't roadmap yet, we plan it after finish i18n. The next big thing - install IONDV app with framework from npmjs.org. As simple node package. Then next big issue - split framework for different packages. You can follow the development in repo https://github.com/iondv/core

About Deno. The iondv. framework implements another task - to rapidly create web applications including rest/soap API and web admin panel with data processing model- registry module. Also including the visual method development in the [IONDV. Studio](https://studio.iondv.com). More like CUBA Platform (java) and possibly Django, but more high-level application development.
